export const SET_PURCHASEREQUESTSINPURCHASEORDER = 'SET_PURCHASEREQUESTSINPURCHASEORDER';
export const SET_PURCHASEREQUESTINPURCHASEORDER = 'SET_PURCHASEREQUESTINPURCHASEORDER';
export const SET_VENDORSINPURCHASEORDER = 'SET_VENDORSINPURCHASEORDER';
