export const SET_PURCHASEREQUESTSINPURCHASEORDER = 'SET_PURCHASEREQUESTSINPURCHASEORDER';
export const SET_PURCHASEREQUESTINPURCHASEORDER = 'SET_PURCHASEREQUESTINPURCHASEORDER';
export const SET_VENDORSINPURCHASEORDER = 'SET_VENDORSINPURCHASEORDER';
export const SET_PROJECTSINPURCHASEORDER = "SET_PROJECTSINPURCHASEORDER";
export const FETCH_PURCHASEORDERS = "FETCH_PURCHASEORDERS";
export const FETCH_PURCHASEORDER_ID = "FETCH_PURCHASEORDER_ID";
export const FETCH_PROJECT = "FETCH_PROJECT";
export const SET_ORDERS_RECEIEVED = "SET_ORDERS_RECEIVED";
