export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_PURCHASEREQUEST = 'ADD_PURCHASEREQUEST';
export const SET_PURCHASEREQUESTS = 'SET_PURCHASEREQUESTS';
export const SET_PURCHASEREQUESTSCOUNT = 'SET_PURCHASEREQUESTSCOUNT';
export const SET_PURCHASEREQUESTDATA = 'SET_PURCHASEREQUESTDATA';
export const SET_PURCHASEREQUESTSUBSCRIPTIONS = 'SET_PURCHASEREQUESTSUBSCRIPTIONS';
