export const FETCH_VENDORS_START = 'FETCH_VENDORS_START';
export const FETCH_VENDORS_SUCCESS = 'FETCH_VENDORS_SUCCESS';
export const FETCH_VENDORS_FAIL = 'FETCH_VENDORS_FAIL';

export const NEW_VENDOR_START = 'NEW_VENDOR_START';
export const NEW_VENDOR_SUCCESS = 'NEW_VENDOR_SUCCESS';
export const NEW_VENDOR_FAIL = 'NEW_VENDOR_FAIL';

export const FETCH_VENDOR = 'FETCH_VENDOR';
