export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_STATEPRODUCTS = 'ADD_STATEPRODUCTS';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';
