/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:f5a4d386-7ef9-4fee-83a2-4a4ba9f4ca0f",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_zKloYkpxS",
    "aws_user_pools_web_client_id": "6c13p3v41ilq4d5sfr9eevc4q4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rnelgzsw2rd3hf2pqkp2f3d224.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
