/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:f4bcff9c-5ec8-4877-90e2-18392a4880f6",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_7gTgQQ7Bp",
    "aws_user_pools_web_client_id": "s2b8afqbabs5obs8766kbjlni",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6xeie7uv6fhktf3omrtdktl47y.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
