export const SET_OPENMODAL = 'SET_OPENMODAL';
export const SET_SHOWSPIN = 'SET_SHOWSPIN';
export const SET_MODALSPIN = 'SET_MODALSPIN';
export const SET_TABLESPIN = 'SET_TABLESPIN';
export const SET_OPENANOTHERMODAL = 'SET_OPENANOTHERMODAL';
