export const SET_OPENMODAL1 = 'SET_OPENMODAL1';
export const SET_OPENMODAL2 = 'SET_OPENMODAL2';
export const SET_SHOWSPIN1 = 'SET_SHOWSPIN1';
export const SET_SHOWSPIN2 = 'SET_SHOWSPIN2';
export const SET_SHOWSPIN3 = 'SET_SHOWSPIN3';
